/* eslint-disable max-len */

type Constants = Readonly<{
  css: {
    units: {
      absoluteLengths: string[];
      relativeLengths: string[];
      lengths: string[];
      angles: string[];
      frequencies: string[];
      gridLengths: string[];
      resolutions: string[];
      times: string[];
    };
    colors: string[];
    properties: Record<string, {
      type: 'any' | 'color' | 'number';
    } | {
      type: 'select';
      values: string[];
    }>;
  };
  html: {
    basicTags: string[];
  };
}>;

const constants: Constants = {
  css: {
    units: {
      absoluteLengths: ['cm', 'mm', 'in', 'px', 'pt', 'pc'],
      relativeLengths: ['em', '%', 'ex', 'ch', 'rem', 'vw', 'vh', 'vmin', 'vmax'],
      lengths: ['cm', 'mm', 'in', 'px', 'pt', 'pc', 'em', '%', 'ex', 'ch', 'rem', 'vw', 'vh', 'vmin', 'vmax'],
      angles: ['deg', 'grad', 'rad', 'turn'],
      frequencies: ['Hz', 'kHz'],
      gridLengths: ['fr'],
      resolutions: ['dpcm', 'dpi', 'dppx', 'x'],
      times: ['ms', 's']
    },
    colors: [
      'black', 'silver', 'gray', 'white', 'maroon', 'red', 'purple', 'fuchsia', 'green', 'lime', 'olive', 'yellow', 'navy', 'blue', 'teal', 'aqua', 'orange', 'aliceblue', 'antiquewhite', 'aquamarine', 'azure', 'beige', 'bisque', 'blanchedalmond', 'blueviolet', 'brown', 'burlywood', 'cadetblue', 'chartreuse', 'chocolate', 'coral', 'cornflowerblue', 'cornsilk', 'crimson', 'cyan', 'darkblue', 'darkcyan', 'darkgoldenrod', 'darkgray', 'darkgreen', 'darkgrey', 'darkkhaki', 'darkmagenta', 'darkolivegreen', 'darkorange', 'darkorchid', 'darkred', 'darksalmon', 'darkseagreen', 'darkslateblue', 'darkslategray', 'darkslategrey', 'darkturquoise', 'darkviolet', 'deeppink', 'deepskyblue', 'dimgray', 'dimgrey', 'dodgerblue', 'firebrick', 'floralwhite', 'forestgreen', 'gainsboro', 'ghostwhite', 'gold', 'goldenrod', 'greenyellow', 'grey', 'honeydew', 'hotpink', 'indianred', 'indigo', 'ivory', 'khaki', 'lavender', 'lavenderblush', 'lawngreen', 'lemonchiffon', 'lightblue', 'lightcoral', 'lightcyan', 'lightgoldenrodyellow', 'lightgray', 'lightgreen', 'lightgrey', 'lightpink', 'lightsalmon', 'lightseagreen', 'lightskyblue', 'lightslategray', 'lightslategrey', 'lightsteelblue', 'lightyellow', 'limegreen', 'linen', 'magenta', 'mediumaquamarine', 'mediumblue', 'mediumorchid', 'mediumpurple', 'mediumseagreen', 'mediumslateblue', 'mediumspringgreen', 'mediumturquoise', 'mediumvioletred', 'midnightblue', 'mintcream', 'mistyrose', 'moccasin', 'navajowhite', 'oldlace', 'olivedrab', 'orangered', 'orchid', 'palegoldenrod', 'palegreen', 'paleturquoise', 'palevioletred', 'papayawhip', 'peachpuff', 'peru', 'pink', 'plum', 'powderblue', 'rosybrown', 'royalblue', 'saddlebrown', 'salmon', 'sandybrown', 'seagreen', 'seashell', 'sienna', 'skyblue', 'slateblue', 'slategray', 'slategrey', 'snow', 'springgreen', 'steelblue', 'tan', 'thistle', 'tomato', 'turquoise', 'violet', 'wheat', 'whitesmoke', 'yellowgreen', 'rebeccapurple'
    ],
    properties: {
      'align-content': { type: 'any' },
      'align-items': { type: 'any' },
      'align-self': { type: 'any' },
      'all': { type: 'select',
        values: ['initial', 'inherit', 'unset', 'revert', 'initial', 'inherit'] },
      'animation': { type: 'any' },
      'animation-delay': { type: 'any' },
      'animation-direction': { type: 'any' },
      'animation-duration': { type: 'any' },
      'animation-fill-mode': { type: 'any' },
      'animation-iteration-count': { type: 'any' },
      'animation-name': { type: 'any' },
      'animation-play-state': { type: 'any' },
      'animation-timing-function': { type: 'any' },
      'appearance': { type: 'select',
        values: ['none', 'auto', 'button', 'textfield', 'searchfield', 'textarea', 'push-button', 'button-bevel', 'slider-horizontal', 'checkbox', 'radio', 'square-button', 'menulist', 'menulist-button', 'listbox', 'meter', 'progress-bar', 'initial', 'inherit'] },
      'aspect-ratio': { type: 'any' },
      'azimuth': { type: 'any' },
      'backdrop-filter': { type: 'any' },
      'backface-visibility': { type: 'select',
        values: ['visible', 'hidden', 'initial', 'inherit'] },
      'background': { type: 'any' },
      'background-attachment': { type: 'any' },
      'background-blend-mode': { type: 'any' },
      'background-clip': { type: 'any' },
      'background-color': { type: 'color' },
      'background-image': { type: 'any' },
      'background-origin': { type: 'any' },
      'background-position': { type: 'any' },
      'background-position-x': { type: 'any' },
      'background-position-y': { type: 'any' },
      'background-repeat': { type: 'any' },
      'background-size': { type: 'any' },
      'block-overflow': { type: 'select',
        values: ['clip', 'ellipsis', 'initial', 'inherit'] },
      'block-size': { type: 'any' },
      'border': { type: 'any' },
      'border-block': { type: 'any' },
      'border-block-color': { type: 'any' },
      'border-block-style': { type: 'any' },
      'border-block-width': { type: 'any' },
      'border-block-end': { type: 'any' },
      'border-block-end-color': { type: 'any' },
      'border-block-end-style': { type: 'any' },
      'border-block-end-width': { type: 'any' },
      'border-block-start': { type: 'any' },
      'border-block-start-color': { type: 'any' },
      'border-block-start-style': { type: 'any' },
      'border-block-start-width': { type: 'any' },
      'border-bottom': { type: 'any' },
      'border-bottom-color': { type: 'any' },
      'border-bottom-left-radius': { type: 'any' },
      'border-bottom-right-radius': { type: 'any' },
      'border-bottom-style': { type: 'select',
        values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'initial', 'inherit'] },
      'border-bottom-width': { type: 'any' },
      'border-collapse': { type: 'select',
        values: ['collapse', 'separate', 'initial', 'inherit'] },
      'border-color': { type: 'any' },
      'border-end-end-radius': { type: 'any' },
      'border-end-start-radius': { type: 'any' },
      'border-image': { type: 'any' },
      'border-image-outset': { type: 'any' },
      'border-image-repeat': { type: 'any' },
      'border-image-slice': { type: 'any' },
      'border-image-source': { type: 'any' },
      'border-image-width': { type: 'any' },
      'border-inline': { type: 'any' },
      'border-inline-end': { type: 'any' },
      'border-inline-color': { type: 'any' },
      'border-inline-style': { type: 'any' },
      'border-inline-width': { type: 'any' },
      'border-inline-end-color': { type: 'any' },
      'border-inline-end-style': { type: 'any' },
      'border-inline-end-width': { type: 'any' },
      'border-inline-start': { type: 'any' },
      'border-inline-start-color': { type: 'any' },
      'border-inline-start-style': { type: 'any' },
      'border-inline-start-width': { type: 'any' },
      'border-left': { type: 'any' },
      'border-left-color': { type: 'color' },
      'border-left-style': { type: 'select',
        values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'initial', 'inherit'] },
      'border-left-width': { type: 'any' },
      'border-radius': { type: 'any' },
      'border-right': { type: 'any' },
      'border-right-color': { type: 'color' },
      'border-right-style': { type: 'select',
        values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'initial', 'inherit'] },
      'border-right-width': { type: 'any' },
      'border-spacing': { type: 'any' },
      'border-start-end-radius': { type: 'any' },
      'border-start-start-radius': { type: 'any' },
      'border-style': { type: 'any' },
      'border-top': { type: 'any' },
      'border-top-color': { type: 'color' },
      'border-top-left-radius': { type: 'any' },
      'border-top-right-radius': { type: 'any' },
      'border-top-style': { type: 'select',
        values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'initial', 'inherit'] },
      'border-top-width': { type: 'any' },
      'border-width': { type: 'any' },
      'bottom': { type: 'any' },
      'box-align': { type: 'select',
        values: ['start', 'center', 'end', 'baseline', 'stretch', 'initial', 'inherit'] },
      'box-decoration-break': { type: 'select',
        values: ['slice', 'clone', 'initial', 'inherit'] },
      'box-direction': { type: 'select',
        values: ['normal', 'reverse', 'inherit', 'initial', 'inherit'] },
      'box-flex': { type: 'number' },
      'box-flex-group': { type: 'any' },
      'box-lines': { type: 'select',
        values: ['single', 'multiple', 'initial', 'inherit'] },
      'box-ordinal-group': { type: 'any' },
      'box-orient': { type: 'select',
        values: ['horizontal', 'vertical', 'inline-axis', 'block-axis', 'inherit', 'initial', 'inherit'] },
      'box-pack': { type: 'select',
        values: ['start', 'center', 'end', 'justify', 'initial', 'inherit'] },
      'box-shadow': { type: 'any' },
      'box-sizing': { type: 'select',
        values: ['content-box', 'border-box', 'initial', 'inherit'] },
      'break-after': { type: 'select',
        values: ['auto', 'avoid', 'always', 'all', 'avoid-page', 'page', 'left', 'right', 'recto', 'verso', 'avoid-column', 'column', 'avoid-region', 'region', 'initial', 'inherit'] },
      'break-before': { type: 'select',
        values: ['auto', 'avoid', 'always', 'all', 'avoid-page', 'page', 'left', 'right', 'recto', 'verso', 'avoid-column', 'column', 'avoid-region', 'region', 'initial', 'inherit'] },
      'break-inside': { type: 'select',
        values: ['auto', 'avoid', 'avoid-page', 'avoid-column', 'avoid-region', 'initial', 'inherit'] },
      'caption-side': { type: 'select',
        values: ['top', 'bottom', 'block-start', 'block-end', 'inline-start', 'inline-end', 'initial', 'inherit'] },
      'caret-color': { type: 'any' },
      'clear': { type: 'select',
        values: ['none', 'left', 'right', 'both', 'inline-start', 'inline-end', 'initial', 'inherit'] },
      'clip': { type: 'any' },
      'clip-path': { type: 'any' },
      'color': { type: 'color' },
      'color-adjust': { type: 'select',
        values: ['economy', 'exact', 'initial', 'inherit'] },
      'column-count': { type: 'any' },
      'column-fill': { type: 'select',
        values: ['auto', 'balance', 'balance-all', 'initial', 'inherit'] },
      'column-gap': { type: 'any' },
      'column-rule': { type: 'any' },
      'column-rule-color': { type: 'color' },
      'column-rule-style': { type: 'any' },
      'column-rule-width': { type: 'any' },
      'column-span': { type: 'select',
        values: ['none', 'all', 'initial', 'inherit'] },
      'column-width': { type: 'any' },
      'columns': { type: 'any' },
      'contain': { type: 'any' },
      'content': { type: 'any' },
      'counter-increment': { type: 'any' },
      'counter-reset': { type: 'any' },
      'counter-set': { type: 'any' },
      'cursor': { type: 'any' },
      'direction': { type: 'select',
        values: ['ltr', 'rtl', 'initial', 'inherit'] },
      'display': { type: 'any' },
      'empty-cells': { type: 'select',
        values: ['show', 'hide', 'initial', 'inherit'] },
      'filter': { type: 'any' },
      'flex': { type: 'any' },
      'flex-basis': { type: 'any' },
      'flex-direction': { type: 'select',
        values: ['row', 'row-reverse', 'column', 'column-reverse', 'initial', 'inherit'] },
      'flex-flow': { type: 'any' },
      'flex-grow': { type: 'number' },
      'flex-shrink': { type: 'number' },
      'flex-wrap': { type: 'select',
        values: ['nowrap', 'wrap', 'wrap-reverse', 'initial', 'inherit'] },
      'float': { type: 'select',
        values: ['left', 'right', 'none', 'inline-start', 'inline-end', 'initial', 'inherit'] },
      'font': { type: 'any' },
      'font-family': { type: 'any' },
      'font-feature-settings': { type: 'any' },
      'font-kerning': { type: 'select',
        values: ['auto', 'normal', 'none', 'initial', 'inherit'] },
      'font-language-override': { type: 'select',
        values: ['normal', 'initial', 'inherit'] },
      'font-optical-sizing': { type: 'select',
        values: ['auto', 'none', 'initial', 'inherit'] },
      'font-variation-settings': { type: 'any' },
      'font-size': { type: 'any' },
      'font-size-adjust': { type: 'any' },
      'font-stretch': { type: 'any' },
      'font-style': { type: 'any' },
      'font-synthesis': { type: 'any' },
      'font-variant': { type: 'any' },
      'font-variant-alternates': { type: 'any' },
      'font-variant-caps': { type: 'select',
        values: ['normal', 'small-caps', 'all-small-caps', 'petite-caps', 'all-petite-caps', 'unicase', 'titling-caps', 'initial', 'inherit'] },
      'font-variant-east-asian': { type: 'any' },
      'font-variant-ligatures': { type: 'any' },
      'font-variant-numeric': { type: 'any' },
      'font-variant-position': { type: 'select',
        values: ['normal', 'sub', 'super', 'initial', 'inherit'] },
      'font-weight': { type: 'any' },
      'gap': { type: 'any' },
      'grid': { type: 'any' },
      'grid-area': { type: 'any' },
      'grid-auto-columns': { type: 'any' },
      'grid-auto-flow': { type: 'any' },
      'grid-auto-rows': { type: 'any' },
      'grid-column': { type: 'any' },
      'grid-column-end': { type: 'any' },
      'grid-column-gap': { type: 'any' },
      'grid-column-start': { type: 'any' },
      'grid-gap': { type: 'any' },
      'grid-row': { type: 'any' },
      'grid-row-end': { type: 'any' },
      'grid-row-gap': { type: 'any' },
      'grid-row-start': { type: 'any' },
      'grid-template': { type: 'any' },
      'grid-template-areas': { type: 'select',
        values: ['none', 'initial', 'inherit'] },
      'grid-template-columns': { type: 'any' },
      'grid-template-rows': { type: 'any' },
      'hanging-punctuation': { type: 'any' },
      'height': { type: 'any' },
      'hyphens': { type: 'select',
        values: ['none', 'manual', 'auto', 'initial', 'inherit'] },
      'image-orientation': { type: 'any' },
      'image-rendering': { type: 'select',
        values: ['auto', 'crisp-edges', 'pixelated', 'initial', 'inherit'] },
      'image-resolution': { type: 'any' },
      'ime-mode': { type: 'select',
        values: ['auto', 'normal', 'active', 'inactive', 'disabled', 'initial', 'inherit'] },
      'initial-letter': { type: 'any' },
      'initial-letter-align': { type: 'any' },
      'inline-size': { type: 'any' },
      'inset': { type: 'any' },
      'inset-block': { type: 'any' },
      'inset-block-end': { type: 'any' },
      'inset-block-start': { type: 'any' },
      'inset-inline': { type: 'any' },
      'inset-inline-end': { type: 'any' },
      'inset-inline-start': { type: 'any' },
      'isolation': { type: 'select',
        values: ['auto', 'isolate', 'initial', 'inherit'] },
      'justify-content': { type: 'any' },
      'justify-items': { type: 'any' },
      'justify-self': { type: 'any' },
      'left': { type: 'any' },
      'letter-spacing': { type: 'any' },
      'line-break': { type: 'select',
        values: ['auto', 'loose', 'normal', 'strict', 'anywhere', 'initial', 'inherit'] },
      'line-clamp': { type: 'any' },
      'line-height': { type: 'any' },
      'line-height-step': { type: 'any' },
      'list-style': { type: 'any' },
      'list-style-image': { type: 'any' },
      'list-style-position': { type: 'select',
        values: ['inside', 'outside', 'initial', 'inherit'] },
      'list-style-type': { type: 'any' },
      'margin': { type: 'any' },
      'margin-block': { type: 'any' },
      'margin-block-end': { type: 'any' },
      'margin-block-start': { type: 'any' },
      'margin-bottom': { type: 'any' },
      'margin-inline': { type: 'any' },
      'margin-inline-end': { type: 'any' },
      'margin-inline-start': { type: 'any' },
      'margin-left': { type: 'any' },
      'margin-right': { type: 'any' },
      'margin-top': { type: 'any' },
      'margin-trim': { type: 'select',
        values: ['none', 'in-flow', 'all', 'initial', 'inherit'] },
      'mask': { type: 'any' },
      'mask-border': { type: 'any' },
      'mask-border-mode': { type: 'select',
        values: ['luminance', 'alpha', 'initial', 'inherit'] },
      'mask-border-outset': { type: 'any' },
      'mask-border-repeat': { type: 'any' },
      'mask-border-slice': { type: 'any' },
      'mask-border-source': { type: 'any' },
      'mask-border-width': { type: 'any' },
      'mask-clip': { type: 'any' },
      'mask-composite': { type: 'any' },
      'mask-image': { type: 'any' },
      'mask-mode': { type: 'any' },
      'mask-origin': { type: 'any' },
      'mask-position': { type: 'any' },
      'mask-repeat': { type: 'any' },
      'mask-size': { type: 'any' },
      'mask-type': { type: 'select',
        values: ['luminance', 'alpha', 'initial', 'inherit'] },
      'max-block-size': { type: 'any' },
      'max-height': { type: 'any' },
      'max-inline-size': { type: 'any' },
      'max-lines': { type: 'any' },
      'max-width': { type: 'any' },
      'min-block-size': { type: 'any' },
      'min-height': { type: 'any' },
      'min-inline-size': { type: 'any' },
      'min-width': { type: 'any' },
      'mix-blend-mode': { type: 'select',
        values: ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity', 'initial', 'inherit'] },
      'object-fit': { type: 'select',
        values: ['fill', 'contain', 'cover', 'none', 'scale-down', 'initial', 'inherit'] },
      'object-position': { type: 'any' },
      'offset': { type: 'any' },
      'offset-anchor': { type: 'any' },
      'offset-distance': { type: 'any' },
      'offset-path': { type: 'any' },
      'offset-position': { type: 'any' },
      'offset-rotate': { type: 'any' },
      'opacity': { type: 'any' },
      'order': { type: 'any' },
      'orphans': { type: 'any' },
      'outline': { type: 'any' },
      'outline-color': { type: 'any' },
      'outline-offset': { type: 'any' },
      'outline-style': { type: 'any' },
      'outline-width': { type: 'any' },
      'overflow': { type: 'any' },
      'overflow-anchor': { type: 'select',
        values: ['auto', 'none', 'initial', 'inherit'] },
      'overflow-block': { type: 'select',
        values: ['visible', 'hidden', 'clip', 'scroll', 'auto', 'initial', 'inherit'] },
      'overflow-clip-box': { type: 'select',
        values: ['padding-box', 'content-box', 'initial', 'inherit'] },
      'overflow-inline': { type: 'select',
        values: ['visible', 'hidden', 'clip', 'scroll', 'auto', 'initial', 'inherit'] },
      'overflow-wrap': { type: 'select',
        values: ['normal', 'break-word', 'anywhere', 'initial', 'inherit'] },
      'overflow-x': { type: 'select',
        values: ['visible', 'hidden', 'clip', 'scroll', 'auto', 'initial', 'inherit'] },
      'overflow-y': { type: 'select',
        values: ['visible', 'hidden', 'clip', 'scroll', 'auto', 'initial', 'inherit'] },
      'overscroll-behavior': { type: 'any' },
      'overscroll-behavior-block': { type: 'select',
        values: ['contain', 'none', 'auto', 'initial', 'inherit'] },
      'overscroll-behavior-inline': { type: 'select',
        values: ['contain', 'none', 'auto', 'initial', 'inherit'] },
      'overscroll-behavior-x': { type: 'select',
        values: ['contain', 'none', 'auto', 'initial', 'inherit'] },
      'overscroll-behavior-y': { type: 'select',
        values: ['contain', 'none', 'auto', 'initial', 'inherit'] },
      'padding': { type: 'any' },
      'padding-block': { type: 'any' },
      'padding-block-end': { type: 'any' },
      'padding-block-start': { type: 'any' },
      'padding-bottom': { type: 'any' },
      'padding-inline': { type: 'any' },
      'padding-inline-end': { type: 'any' },
      'padding-inline-start': { type: 'any' },
      'padding-left': { type: 'any' },
      'padding-right': { type: 'any' },
      'padding-top': { type: 'any' },
      'page-break-after': { type: 'select',
        values: ['auto', 'always', 'avoid', 'left', 'right', 'recto', 'verso', 'initial', 'inherit'] },
      'page-break-before': { type: 'select',
        values: ['auto', 'always', 'avoid', 'left', 'right', 'recto', 'verso', 'initial', 'inherit'] },
      'page-break-inside': { type: 'select',
        values: ['auto', 'avoid', 'initial', 'inherit'] },
      'paint-order': { type: 'any' },
      'perspective': { type: 'any' },
      'perspective-origin': { type: 'any' },
      'place-content': { type: 'any' },
      'place-items': { type: 'any' },
      'place-self': { type: 'any' },
      'pointer-events': { type: 'select',
        values: ['auto', 'none', 'visiblePainted', 'visibleFill', 'visibleStroke', 'visible', 'painted', 'fill', 'stroke', 'all', 'inherit', 'initial', 'inherit'] },
      'position': { type: 'select',
        values: ['static', 'relative', 'absolute', 'sticky', 'fixed', 'initial', 'inherit'] },
      'quotes': { type: 'any' },
      'resize': { type: 'select',
        values: ['none', 'both', 'horizontal', 'vertical', 'block', 'inline', 'initial', 'inherit'] },
      'right': { type: 'any' },
      'rotate': { type: 'any' },
      'row-gap': { type: 'any' },
      'ruby-align': { type: 'select',
        values: ['start', 'center', 'space-between', 'space-around', 'initial', 'inherit'] },
      'ruby-merge': { type: 'select',
        values: ['separate', 'collapse', 'auto', 'initial', 'inherit'] },
      'ruby-position': { type: 'select',
        values: ['over', 'under', 'inter-character', 'initial', 'inherit'] },
      'scale': { type: 'any' },
      'scrollbar-color': { type: 'any' },
      'scrollbar-width': { type: 'select',
        values: ['auto', 'thin', 'none', 'initial', 'inherit'] },
      'scroll-behavior': { type: 'select',
        values: ['auto', 'smooth', 'initial', 'inherit'] },
      'scroll-margin': { type: 'any' },
      'scroll-margin-block': { type: 'any' },
      'scroll-margin-block-start': { type: 'any' },
      'scroll-margin-block-end': { type: 'any' },
      'scroll-margin-bottom': { type: 'any' },
      'scroll-margin-inline': { type: 'any' },
      'scroll-margin-inline-start': { type: 'any' },
      'scroll-margin-inline-end': { type: 'any' },
      'scroll-margin-left': { type: 'any' },
      'scroll-margin-right': { type: 'any' },
      'scroll-margin-top': { type: 'any' },
      'scroll-padding': { type: 'any' },
      'scroll-padding-block': { type: 'any' },
      'scroll-padding-block-start': { type: 'any' },
      'scroll-padding-block-end': { type: 'any' },
      'scroll-padding-bottom': { type: 'any' },
      'scroll-padding-inline': { type: 'any' },
      'scroll-padding-inline-start': { type: 'any' },
      'scroll-padding-inline-end': { type: 'any' },
      'scroll-padding-left': { type: 'any' },
      'scroll-padding-right': { type: 'any' },
      'scroll-padding-top': { type: 'any' },
      'scroll-snap-align': { type: 'any' },
      'scroll-snap-coordinate': { type: 'any' },
      'scroll-snap-destination': { type: 'any' },
      'scroll-snap-points-x': { type: 'any' },
      'scroll-snap-points-y': { type: 'any' },
      'scroll-snap-stop': { type: 'select',
        values: ['normal', 'always', 'initial', 'inherit'] },
      'scroll-snap-type': { type: 'any' },
      'scroll-snap-type-x': { type: 'select',
        values: ['none', 'mandatory', 'proximity', 'initial', 'inherit'] },
      'scroll-snap-type-y': { type: 'select',
        values: ['none', 'mandatory', 'proximity', 'initial', 'inherit'] },
      'shape-image-threshold': { type: 'any' },
      'shape-margin': { type: 'any' },
      'shape-outside': { type: 'any' },
      'tab-size': { type: 'any' },
      'table-layout': { type: 'select',
        values: ['auto', 'fixed', 'initial', 'inherit'] },
      'text-align': { type: 'select',
        values: ['start', 'end', 'left', 'right', 'center', 'justify', 'match-parent', 'initial', 'inherit'] },
      'text-align-last': { type: 'select',
        values: ['auto', 'start', 'end', 'left', 'right', 'center', 'justify', 'initial', 'inherit'] },
      'text-combine-upright': { type: 'any' },
      'text-decoration': { type: 'any' },
      'text-decoration-color': { type: 'color' },
      'text-decoration-line': { type: 'any' },
      'text-decoration-skip': { type: 'any' },
      'text-decoration-skip-ink': { type: 'select',
        values: ['auto', 'all', 'none', 'initial', 'inherit'] },
      'text-decoration-style': { type: 'select',
        values: ['solid', 'double', 'dotted', 'dashed', 'wavy', 'initial', 'inherit'] },
      'text-decoration-thickness': { type: 'any' },
      'text-emphasis': { type: 'any' },
      'text-emphasis-color': { type: 'color' },
      'text-emphasis-position': { type: 'any' },
      'text-emphasis-style': { type: 'any' },
      'text-indent': { type: 'any' },
      'text-justify': { type: 'select',
        values: ['auto', 'inter-character', 'inter-word', 'none', 'initial', 'inherit'] },
      'text-orientation': { type: 'select',
        values: ['mixed', 'upright', 'sideways', 'initial', 'inherit'] },
      'text-overflow': { type: 'any' },
      'text-rendering': { type: 'select',
        values: ['auto', 'optimizeSpeed', 'optimizeLegibility', 'geometricPrecision', 'initial', 'inherit'] },
      'text-shadow': { type: 'any' },
      'text-size-adjust': { type: 'any' },
      'text-transform': { type: 'select',
        values: ['none', 'capitalize', 'uppercase', 'lowercase', 'full-width', 'full-size-kana', 'initial', 'inherit'] },
      'text-underline-offset': { type: 'any' },
      'text-underline-position': { type: 'any' },
      'top': { type: 'any' },
      'touch-action': { type: 'any' },
      'transform': { type: 'any' },
      'transform-box': { type: 'select',
        values: ['border-box', 'fill-box', 'view-box', 'initial', 'inherit'] },
      'transform-origin': { type: 'any' },
      'transform-style': { type: 'any' },
      'transition': { type: 'any' },
      'transition-delay': { type: 'any' },
      'transition-duration': { type: 'any' },
      'transition-property': { type: 'any' },
      'transition-timing-function': { type: 'any' },
      'translate': { type: 'any' },
      'unicode-bidi': { type: 'select',
        values: ['normal', 'embed', 'isolate', 'bidi-override', 'isolate-override', 'plaintext', 'initial', 'inherit'] },
      'user-select': { type: 'select',
        values: ['auto', 'text', 'none', 'contain', 'all', 'initial', 'inherit'] },
      'vertical-align': { type: 'any' },
      'visibility': { type: 'select',
        values: ['visible', 'hidden', 'collapse', 'initial', 'inherit'] },
      'white-space': { type: 'select',
        values: ['normal', 'pre', 'nowrap', 'pre-wrap', 'pre-line', 'break-spaces', 'initial', 'inherit'] },
      'widows': { type: 'any' },
      'width': { type: 'any' },
      'will-change': { type: 'any' },
      'word-break': { type: 'select',
        values: ['normal', 'break-all', 'keep-all', 'break-word', 'initial', 'inherit'] },
      'word-spacing': { type: 'any' },
      'word-wrap': { type: 'select',
        values: ['normal', 'break-word', 'initial', 'inherit'] },
      'writing-mode': { type: 'select',
        values: ['horizontal-tb', 'vertical-rl', 'vertical-lr', 'sideways-rl', 'sideways-lr', 'initial', 'inherit'] },
      'z-index': { type: 'any' },
      'zoom': { type: 'any' },
    }
  },
  html: {
    basicTags: [
      'a', 'b', 'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
      'hr', 'ol', 'p', 'span', 'u', 'ul'
    ]
  }
};

export default constants;